# Generated by Django 6.0.7 on 2026-07-21 09:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('embed', 5), ('quote', 8), ('checklist', 13), ('simple_list', 17), ('pros_cons', 22), ('stat', 26), ('gallery', 30), ('faq', 35), ('callout', 39)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Подзаголовок'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'ol', 'ul', 'link', 'hr', 'blockquote'], 'icon': 'pilcrow', 'label': 'Текст'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Ссылка на YouTube, Яндекс.Карты, Google Maps и т.д.', 'icon': 'media', 'label': 'Embed (видео / карта)'}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Текст цитаты'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Автор', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('text', 6), ('author', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Текст пункта'}), 10: ('wagtail.blocks.BooleanBlock', (), {'label': 'Отмечено по умолчанию', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('label', 9), ('checked', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Пункты'}), 13: ('wagtail.blocks.StructBlock', [[('items', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Элемент'}), 15: ('wagtail.blocks.ListBlock', (14,), {'label': 'Элементы списка'}), 16: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Нумерованный', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('items', 15), ('ordered', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Плюс'}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Плюсы'}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Минус'}), 21: ('wagtail.blocks.ListBlock', (20,), {'label': 'Минусы'}), 22: ('wagtail.blocks.StructBlock', [[('pros', 19), ('cons', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: 150, 2.5 млн, +35%', 'label': 'Значение'}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись'}), 25: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Доп. описание', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('value', 23), ('label', 24), ('description', 25)]], {}), 27: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 28: ('wagtail.blocks.StructBlock', [[('image', 27), ('caption', 3)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'label': 'Изображения'}), 30: ('wagtail.blocks.StructBlock', [[('images', 29)]], {}), 31: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос'}), 32: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'label': 'Ответ'}), 33: ('wagtail.blocks.StructBlock', [[('question', 31), ('answer', 32)]], {}), 34: ('wagtail.blocks.ListBlock', (33,), {'label': 'Вопросы и ответы'}), 35: ('wagtail.blocks.StructBlock', [[('items', 34)]], {}), 36: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Информация'), ('warning', 'Предупреждение'), ('success', 'Успех'), ('danger', 'Важно')], 'label': 'Тип'}), 37: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Текст'}), 38: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: fa-info-circle', 'label': 'Иконка (CSS-класс)', 'required': False}), 39: ('wagtail.blocks.StructBlock', [[('type', 36), ('text', 37), ('icon', 38)]], {})}),
        ),
    ]
