# Generated by Django 6.0.7 on 2026-07-22 12:04

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_location_slug_alter_newscategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('embed', 7), ('quote', 10), ('checklist', 15), ('simple_list', 19), ('pros_cons', 24), ('stat', 28), ('gallery', 32), ('faq', 37), ('callout', 41)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'label': 'Уровень заголовка'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Текст заголовка'}), 2: ('wagtail.blocks.StructBlock', [[('level', 0), ('text', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'ol', 'ul', 'link', 'hr', 'blockquote'], 'icon': 'pilcrow', 'label': 'Текст'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Ссылка на YouTube, Яндекс.Карты, Google Maps и т.д.', 'icon': 'media', 'label': 'Embed (видео / карта)'}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Текст цитаты'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Автор', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 8), ('author', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Текст пункта'}), 12: ('wagtail.blocks.BooleanBlock', (), {'label': 'Отмечено по умолчанию', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('label', 11), ('checked', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'Пункты'}), 15: ('wagtail.blocks.StructBlock', [[('items', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Элемент'}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Элементы списка'}), 18: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Нумерованный', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('items', 17), ('ordered', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Плюс'}), 21: ('wagtail.blocks.ListBlock', (20,), {'label': 'Плюсы'}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Минус'}), 23: ('wagtail.blocks.ListBlock', (22,), {'label': 'Минусы'}), 24: ('wagtail.blocks.StructBlock', [[('pros', 21), ('cons', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: 150, 2.5 млн, +35%', 'label': 'Значение'}), 26: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись'}), 27: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Доп. описание', 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('value', 25), ('label', 26), ('description', 27)]], {}), 29: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 30: ('wagtail.blocks.StructBlock', [[('image', 29), ('caption', 5)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'label': 'Изображения'}), 32: ('wagtail.blocks.StructBlock', [[('images', 31)]], {}), 33: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос'}), 34: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'label': 'Ответ'}), 35: ('wagtail.blocks.StructBlock', [[('question', 33), ('answer', 34)]], {}), 36: ('wagtail.blocks.ListBlock', (35,), {'label': 'Вопросы и ответы'}), 37: ('wagtail.blocks.StructBlock', [[('items', 36)]], {}), 38: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Информация'), ('warning', 'Предупреждение'), ('success', 'Успех'), ('danger', 'Важно')], 'label': 'Тип'}), 39: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Текст'}), 40: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: fa-info-circle', 'label': 'Иконка (CSS-класс)', 'required': False}), 41: ('wagtail.blocks.StructBlock', [[('type', 38), ('text', 39), ('icon', 40)]], {})}, verbose_name='Основное содержание'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, verbose_name='Анонс'),
        ),
    ]
