# Generated by Django 6.0.7 on 2026-07-22 13:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newspage_body_alter_newspage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='intro',
            field=wagtail.fields.RichTextField(verbose_name='Анонс'),
        ),
    ]
