# Generated by Django 5.0.9 on 2026-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False, help_text='Если включено, эта страница заменит ленту постов на /', verbose_name='Использовать как главную страницу'),
        ),
    ]
