# Generated by Django 6.0.7 on 2026-07-19 06:21

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nlp', '0001_enable_pgvector'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(blank=True)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('sentiment_polarity', models.FloatField(blank=True, null=True)),
                ('sentiment_subjectivity', models.FloatField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('error', models.TextField(blank=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nlp_analysis', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Результат NLP-анализа страницы',
                'verbose_name_plural': 'Результаты NLP-анализа страниц',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='pageanalysis_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
