# Generated by Django 5.0.9 on 2026-07-14 11:25

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_polarity', models.FloatField(blank=True, null=True)),
                ('sentiment_subjectivity', models.FloatField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=200)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_stale', models.BooleanField(default=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='content.post')),
            ],
            options={
                'verbose_name': 'NLP-анализ записи',
                'verbose_name_plural': 'NLP-анализ записей',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='post_embedding_hnsw_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='PostEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('label', models.CharField(max_length=50)),
                ('start_char', models.IntegerField()),
                ('end_char', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='content.post')),
            ],
            options={
                'verbose_name': 'Именованная сущность',
                'verbose_name_plural': 'Именованные сущности',
                'indexes': [models.Index(fields=['post', 'label'], name='nlp_postent_post_id_3ece68_idx')],
            },
        ),
    ]
